version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitnet
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  rabbitnet:
    external: true

volumes:
  rabbitmq_data:
